### ISSUE TITLE
Just a simple question about the power curve

### ISSUE THREAD

**Issue by abooda1981** [IEAWindTask37/IEA-22-280-RWT#101]
Hello, I realise that this might be a very rookie question, but where is the power curve data I could use to model this turbine from, say, Excel? Basically I would want to do something like recreate the wind speed vs power output chart shown in the reports. 

Many thanks.

**Comment by gbarter** [comment]
Please see the Excel file in the [Documentation](https://github.com/IEAWindTask37/IEA-22-280-RWT/tree/main/Documentation) folder.

**Comment by abooda1981** [comment]
Many thanks!
