### ISSUE TITLE
What is the rated wind speed of this wind turbine

### ISSUE THREAD

**Issue by FSI-in** [IEAWindTask37/IEA-22-280-RWT#24]
Dear all,
Please ask, what is the rated wind speed and rated speed of this wind turbine, and where should I find these parameters.
Thank you all

**Comment by ptrbortolotti** [comment]
My apologies for the slow reply. We were actively working on the model, which has now been fixed. A technical report describing it will be published in the coming months. The report lists a rated wind speed of 11 m/s

**Comment by FSI-in** [comment]
Ok, thanks for your reply, have a nice life!
