### ISSUE TITLE
Error in WindIO file

### ISSUE THREAD

**Issue by pelljam** [IEAWindTask37/IEA-22-280-RWT#32]
I know this is a work in progress still, but I've noticed the aerfoil coefficients look wrong in the WindIO file for:

> name: FFA-W3-211
> configuration: Transitional flow, N=7

Specifically the grid and values are almost the same, e.g.:

> c_l: 
>   grid: [-3.141592653589793, -3.1016994135442086, -3.0618061734986237, ...
>   values: [-3.141592653589793, -3.1016994135442086, -3.0618061734986237,...

I'm not sure which of the airfoil configurations you use in the OpenFAST model, or if it is an average across configurations, or if the WindIO file is even used directly to generate the model? But possibly this is feeding an error into the model. 

Cheers, 

James Pell

**Comment by fzahle** [comment]
Thanks for reporting this. Yes, we also spotted this bug a few days ago and it’s on me to fix it. I’ll let you know in this issue when it’s fixed.

The default airfoil data used in both the HAWC2 and OpenFAST models is the mixed airfoil data (the first set in the list).

**Comment by fzahle** [comment]
now fixed in master along with a bunch of other things
