### ISSUE TITLE
gelcoat Xt, Xc values are wrong

### ISSUE THREAD

**Issue by fzahle** [IEAWindTask37/IEA-22-280-RWT#4]
https://github.com/IEAWindTask37/IEA-22-280-RWT/blob/main/windIO/IEA-22-280-RWT.yaml#L836
this is also an issue in the data for the IEA 15 MW. Should it be Xt=74**e6**?

**Comment by ptrbortolotti** [comment]
I've pushed the fix to https://github.com/IEAWindTask37/IEA-22-280-RWT/pull/3, although I really can't say where the gelcoat properties come from...

**Comment by fzahle** [comment]
Great, I guess gelcoat properties just need to be set to something that doesn't make it fail.
