### ISSUE TITLE
Unsteady controller at high (>23m/s) steady wind speeds 

### ISSUE THREAD

**Issue by MSaraber** [IEAWindTask37/IEA-22-280-RWT#72]
I am running simulations of the IEA 22MW turbine for steady wind speeds in range 3-25 m/s. For wind speeds larger than 23m/s I see the rotor speed fluctuates between 5.5rmp and 8.5rpm. Looking at the blade pitch large deviations can also be concluded. Am I doing something wrong is something happening in the tuning at these high wind speeds?  I am no control expert, but these figures don't look correct. 

I am using ROSCO version 2.9.0 controller. 

Look forward to a reply. 
<img width="342" alt="RotSpeed23ms" src="https://github.com/IEAWindTask37/IEA-22-280-RWT/assets/156674878/db23a714-ae62-4541-8c2d-9c3c4066c48a">
<img width="335" alt="BLPitch23ms" src="https://github.com/IEAWindTask37/IEA-22-280-RWT/assets/156674878/be8e4093-56a4-408a-a211-76f0eecc58f2">

**Comment by ptrbortolotti** [comment]
I suppose you are using BeamDyn, am I right? If so, I'm aware of the issue, which I've investigated at length. So far I've concluded that the model is unstable at high winds (>22m/s). However a paper will appear at TORQUE 2024 showing that HAWC2, Bladed, and QBlade do not experience this instability. I'm still working on it and I'll share more updates as I get them

**Comment by ptrbortolotti** [comment]
@dzalkind I haven't run much of ElastoDyn for the blades. Have you seen this happening?

**Comment by dzalkind** [comment]
@MSaraber, thanks for making us aware of this!  There were issues with the gains, which I have addressed in #74.  I tested locally and it seemed to work fine at cut-out wind speeds.

**Comment by MSaraber** [comment]
Its also working for me now. Thanks for the help!
