### ISSUE TITLE
OpenFAST Cd0 always zero

### ISSUE THREAD

**Issue by pelljam** [IEAWindTask37/IEA-22-280-RWT#73]
Hi, 

I just wondered if it was intentional that Cd0 (2D drag coefficient value at 0-lift) is zero for all airfoils? 

Thanks, 

James

**Comment by ptrbortolotti** [comment]
I've pushed new airfoil files here https://github.com/IEAWindTask37/IEA-22-280-RWT/tree/openfast_fixes
I'm running some tests to make sure they perform as expected

**Comment by ptrbortolotti** [comment]
Hello again,
Once merged, this PR https://github.com/IEAWindTask37/IEA-22-280-RWT/pull/75 will fix the issue of Cd0. Note however that I haven't seen much effect (almost anything) in the time-domain turbulent-wind results. I have not processed the linearized-domain results yet. However generating a good Campbell by linearizing the OpenFAST with unsteady aero airfoil turned on is a little time consuming at the moment, so this will take me a while

**Comment by pelljam** [comment]
Thanks Pietro. For what it's worth, I observed a noticeable difference between OrcaFlex and OpenFAST, in some time-domain results, which I can attribute to this data (because once I set Cd0 for all airfoils in OrcaFlex, the results converged). Although off the top of my head, I can't remember the details. I can have a closer look, if you are interested? Which UA model are you running? My investigation uses the González model, possibly that choice will dictate the sensitivity to this data?

**Comment by ptrbortolotti** [comment]
I've been toggling between UAMod 3, which works better with ElastoDyn (@dzalkind can confirm), and UAMod 4, which works better for BeamDyn. We suspect that there is a dependency to the time step size, which must be very small with BeamDyn (we are close to fixing that). The two models are different implementations of the Beddoes-Leishman unsteady aero model https://openfast.readthedocs.io/en/main/source/user/aerodyn/theory_ua.html#beddoes-leishman-4-states-model-uamod-4
