### ISSUE TITLE
Nacelle inertia

### ISSUE THREAD

**Issue by pelljam** [IEAWindTask37/IEA-22-280-RWT#82]
Hello,

In the windIO file the nacelle inertia is given as:

`
system_inertia: [11242533.974662142, 14539734.272247598, 14648892.347010525, 799429.7807778214, 2997469.283520137, -290639.9124403294]
`
The windIO doc described this as:

> Mass moments of inertia of the nacelle system. Ixx, Iyy, Izz, Ixy, Ixz, Iyz are expressed in the yaw-aligned coordinate system.

In the turbine documentation,  Ixx, Iyy, Izz (Table 11), it is given as

`
Nacelle no hub/yaw 1.25E+07 1.62E+07 1.68E+07
`

This is described as: 

> whereas the mass moments of inertia are defined with respect to coordinate systems whose origins are defined at the center of mass of each component, and the axes are oriented as the TT coordinate system

I am just struggling to reconcile these two set of inertia data?  But then I'm not exactly 100% sure at what origin and with respect to which frame the windIO inertia there is given in?  Is the "yaw-aligned coordinate system" axes different to the TT coordinate system? 

Note I can see the inertia defined at the TT origin with respect the TT coordinate system are consistent. 

Thanks, James

**Comment by ptrbortolotti** [comment]
Hello James, I have a fresh new laptop and I'm struggling to run WISDEM and WEIS. I will get back to you asap on this

**Comment by ptrbortolotti** [comment]
James, thank you for catching a (very likely) typo.

I've run a few checks and I can't explain anymore those 3 entries in Table 11 the report
`Nacelle no hub/yaw 1.25E+07 1.62E+07 1.68E+07`

Good news: the values in the windIO yaml and in OpenFAST look correct, so please move ahead with
`Nacelle no hub/yaw 1.12E+07 1.45E+07 1.46E+07`

The other entries in Table 11 also look correct, except for X_{TT}, which should be negative at `-5.85`

Please let me know if this clarifies your doubts. In the meanwhile I will get a Wiki page going like in the IEA15 https://github.com/IEAWindTask37/IEA-15-240-RWT/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by pelljam** [comment]
Great, thank you for the clarification.
