### ISSUE TITLE
Pitch control issue

### ISSUE THREAD

**Issue by UmayerH** [IEAWindTask37/IEA-22-280-RWT#86]
Hi all,

I am running a simulation under a turbulent wind with a mean wind speed of 11.5 m/s and I am noticing that the turbine is not pitching correctly. I am expecting that the turbine pitches to maintain the rated power but this is not happening. I have set the initial conditions for pitch and rotor speed to the values that are expected to be close to the mean wind speed and have set the following DOF to True:

FlapDOF1
FlapDOF2
EdgeDOF 
GenDOF
TwFADOF1 
TwFADOF2
TwSSDOF1    
TwSSDOF2  

Are there any suggestions? I am also receiving the following messages:

************************************************************************************************** 
OpenFAST 
 
Copyright (C) 2023 National Renewable Energy Laboratory 
Copyright (C) 2023 Envision Energy USA LTD 
 
This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY. 
See the "LICENSE" file distributed with this software for details. 
************************************************************************************************** 
 
OpenFAST-v3.5.1 
Compile Info: 
 - Compiler: Intel(R) Fortran Compiler 2021 
 - Architecture: 64 bit 
 - Precision: single 
 - OpenMP: No 
 - Date: Oct 20 2023 
 - Time: 13:40:29 
Execution Info: 
 - Date: 06/06/2024 
 - Time: 12:15:45+0200 
 
OpenFAST input file heading: 
    Generated with AeroElasticSE FAST driver 
 
Running ElastoDyn. 
Nodal outputs section of ElastoDyn input file not found or improperly formatted. 
Running BeamDyn. 
Nodal outputs section of BeamDyn input file not found or improperly formatted. 
Running BeamDyn. 
Nodal outputs section of BeamDyn input file not found or improperly formatted. 
Running BeamDyn. 
Nodal outputs section of BeamDyn input file not found or improperly formatted. 
Running AeroDyn. 
AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted. 
Skipping nodal outputs. 
Running InflowWind. 
 
   Reading a 35x35 grid (340 m wide, 0 m to 340 m above ground) with a characteristic wind speed 
   of 11.458 m/s. 
 
   Processed 2800 time steps of 4-Hz full-field data (699.75 seconds). 
Running ServoDyn. 
Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows). 
Using legacy Bladed DLL interface. 
 
FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 
FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 
FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 
 
 Time: 0 of 400 seconds.                                                                                
------------------------------------------------------------------------------
Running ROSCO-v2.8.0
A wind turbine controller framework for public use in the scientific field    
Developed in collaboration: National Renewable Energy Laboratory              
                            Delft University of Technology, The Netherlands   
------------------------------------------------------------------------------ 
Generator speed:    7.0 RPM, Pitch angle:   3.6 deg, Power:     0.0 kW, Est. wind Speed:  10.7 m/s 

 
FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOu 
tput(node 3, blade 1):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle 
of attack or low relative velocity. This warning will not be repeated though the condition may 
persist. 
 
 
FAST_Solution:FAST_AdvanceStates:SrvD_UpdateStates:DLL_controller_call:BladedInterface option was 
designed for an explicit-loose coupling scheme. Using last calculated values from DLL on all 
subsequent calls until time is advanced. Warning will not be displayed again. 
 
 
FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:BEMT_UpdateStates(node 1, blade 
1):ComputeTau:Rotor-averaged axial induction factor is greater than 0.5; limiting time-varying 
tau1. This message will not be repeated though the condition may persist.

![bld1pitch](https://github.com/IEAWindTask37/IEA-22-280-RWT/assets/141555589/6f373e4e-9e22-4193-adfb-d881100c2ef7)
![genspeed](https://github.com/IEAWindTask37/IEA-22-280-RWT/assets/141555589/faf09d2f-6dfb-4a8e-bcc5-d79b30d705d9)

**Comment by ptrbortolotti** [comment]
Hello,
I attach the files that I generated to run turbulent wind at 11 m/s. Try comparing files and see what's different.
I hope this helps.

[github.zip](https://github.com/user-attachments/files/15744954/github.zip)

best regards,
Pietro

**Comment by ptrbortolotti** [comment]
Unfortunately the wind files are too large for GitHub, and I uploaded them on retransfer https://we.tl/t-lmAeV5G0SA

**Comment by UmayerH** [comment]
> Unfortunately the wind files are too large for GitHub, and I uploaded them on retransfer https://we.tl/t-lmAeV5G0SA

Hi Pietro,

Thank you for sharing your files. I just have a question about your Aerodyn file, I see you set WakeMode=11. Is this a typo or is this really a feature in Openfast? I don't see this in the manual.

**Comment by ptrbortolotti** [comment]
it is a real feature, it will be documented soon. It's a new implementation of the BEM performed by my former colleague Emmanuel Branlard. You can also set WakeMod=1, results for this rotor won't change a whole lot

**Comment by UmayerH** [comment]
I see. Thank you for your suggestion however I have one question. I am simulating under a turbulent wind and so that's why I don't think using steady BEM is suitable, could you explain why is it ok to use WakeMod=1 like you suggested?

**Comment by ptrbortolotti** [comment]
From OpenFAST documentation:

_Set WakeMod to 0 if you want to disable rotor wake/induction effects or 1 to include these effects using the (quasi-steady) BEM theory model. When WakeMod is set to 2, a dynamic BEM theory model (DBEMT) is used (also referred to as dynamic inflow or dynamic wake model, see [Section 4.2.1.7.2](https://openfast.readthedocs.io/en/main/source/user/aerodyn/theory.html#ad-dbemt)). When WakeMod is set to 3, the free vortex wake model is used, also referred to as OLAF (see [Section 4.2.2](https://openfast.readthedocs.io/en/main/source/user/aerodyn-olaf/index.html#olaf)). WakeMod cannot be set to 2 or 3 during linearization analyses._

The new implementation applies to `WakeMod` 1 and 2, and can be activated by setting `WakeMod` to 11 or 12. I did see some convergence issues with `WakeMod = 12` (we have not yet had the time to investigate the issue) but you are good to run `WakeMod = 2`.
