### ISSUE TITLE
BeamDyn vs ElastoDyn blade sections properties

### ISSUE THREAD

**Issue by miliante** [IEAWindTask37/IEA-22-280-RWT#90]
Hello,

I am trying to compile the IEA-22-280-RWT into a database of properties for running OpenFAST, and concurrently trying to understand the input s in the files. For BeamDyn_blade and Elastodyn_blade files I expected the properties to be the same, as they are reflecting the same BlFract.
Nevertheless, I found some differences in the values. Is the difference due to some interpolation or using different software to calculate the properties, or they are indeed supposed to be different?
The 6x6 Stiffness Matrix for a section is very coupled, while the BeamDyn manual refers to a diagonal uncoupled matrix. As before, is this coupling due the use of an external software to calculate the properties? If so, which one was used?

Thank you for your help

**Comment by ptrbortolotti** [comment]
Hello @miliante,
You are correct, the BD and ED blade files differ slightly. The BD file was converted straight from HAWC2 and was verified in this paper https://iopscience.iop.org/article/10.1088/1742-6596/2767/5/052042. The HAWC2 files were generated at DTU using the design framework AESOpt, which leverages the Becas cross sectional solver. BD supports fully populated 6x6 matrices.
The ED blade file was generated using the [WEIS framework](https://github.com/WISDEM/WEIS), which leverages the [PreComp cross sectional solver](https://www.nrel.gov/wind/nwtc/precomp.html). 
Does this answer your doubts?
BR

**Comment by miliante** [comment]
Hello @ptrbortolotti 
Thank you for such a prompt reply. Indeed, it answers my question. This confirms that, physically, they are the same, even if there are some slight differences. I am acquainted with the PreComp solver, but AESOpt/Becas is new to me. I will try to search on how these matrices, particularly stiffness, were built and if I can simplify it in my properties DB.

THank you again for your support.

**Comment by ptrbortolotti** [comment]
hello @miliante , I will close this issue now. Note that @KIDEVLIN has been working on a new open-source workflow to generate 6x6 K and I matrices. You can find an example here https://github.com/KIDEVLIN/SONATA/tree/SONATAmini/examples/2_IEA22MW
