### ISSUE TITLE
Edgewise and flapwise deflections and moments not showing

### ISSUE THREAD

**Issue by FannyICY** [IEAWindTask37/IEA-22-280-RWT#91]
Hello everyone.

I'm running simulations of the IEA 22MW with OpenFAST, with a mean turbulent wind speed of 6mps. I also set the DOF as follows

True                   FlapDOF1    - First flapwise blade mode DOF (flag)	
True                   FlapDOF2    - Second flapwise blade mode DOF (flag)	
True                   EdgeDOF     - First edgewise blade mode DOF (flag)	
False                  TeetDOF     - Rotor-teeter DOF (flag) [unused for 3 blades]	
False                  DrTrDOF     - Drivetrain rotational-flexibility DOF (flag)	
True                   GenDOF      - Generator DOF (flag)	
False                  YawDOF      - Yaw DOF (flag)	
True                   TwFADOF1    - First fore-aft tower bending-mode DOF (flag)	
True                   TwFADOF2    - Second fore-aft tower bending-mode DOF (flag)	
True                   TwSSDOF1    - First side-to-side tower bending-mode DOF (flag)	
True                   TwSSDOF2    - Second side-to-side tower bending-mode DOF (flag)	
False                  PtfmSgDOF   - Platform horizontal surge translation DOF (flag)	
False                  PtfmSwDOF   - Platform horizontal sway translation DOF (flag)	
False                  PtfmHvDOF   - Platform vertical heave translation DOF (flag)	
False                  PtfmRDOF    - Platform roll tilt rotation DOF (flag)	
False                  PtfmPDOF    - Platform pitch tilt rotation DOF (flag)	
False                  PtfmYDOF    - Platform yaw rotation DOF (flag)	
 
I'd like to output edgewise and flapwise deflections of the blades using the following output names.

"TipDxb1"                 - Blade 1 flapwise tip deflection (relative to the undeflected position)	
"TipDyb1"                 - Blade 1 edgewise tip deflection (relative to the undeflected position)	
"TipDxb2"                 - Blade 2 flapwise tip deflection (relative to the undeflected position)	
"TipDyb2"                 - Blade 2 edgewise tip deflection (relative to the undeflected position)	
"TipDxb3"                 - Blade 3 flapwise tip deflection (relative to the undeflected position)	
"TipDyb3"                 - Blade 3 edgewise tip deflection (relative to the undeflected position)	
"RootMxb1"                - Blade 1 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMEdg1"               - Blade 1 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMyb1"                - Blade 1 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	
"RootMFlp1"               - Blade 1 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	
"RootMxb2"                - Blade 2 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMEdg2"               - Blade 2 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMyb2"                - Blade 2 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	
"RootMFlp2"               - Blade 2 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	
"RootMxb3"                - Blade 3 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMEdg3"               - Blade 3 edgewise moment (i.e., the moment caused by edgewise forces) at the blade root	
"RootMyb3"                - Blade 3 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	
"RootMFlp3"               - Blade 3 flapwise moment (i.e., the moment caused by flapwise forces) at the blade root	

The problem is that my plots show that these edgewise and flapwise values are constantly 0, which I doubt. On top of that, pyDatView recognizes them as "NVALI".

The OpenFAST simulation took 12 hours approximately with the following messages.

> ************************************************************************************************** 
> OpenFAST 
>  
> Copyright (C) 2024 National Renewable Energy Laboratory 
> Copyright (C) 2024 Envision Energy USA LTD 
>  
> This program is licensed under Apache License Version 2.0 and comes with ABSOLUTELY NO WARRANTY. 
> See the "LICENSE" file distributed with this software for details. 
> ************************************************************************************************** 
>  
> OpenFAST-v3.5.3 
> Compile Info: 
>  - Compiler: Intel(R) Fortran Compiler 2021 
>  - Architecture: 64 bit 
>  - Precision: single 
>  - OpenMP: No 
>  - Date: Apr 11 2024 
>  - Time: 20:51:36 
> Execution Info: 
>  - Date: 06/27/2024 
>  - Time: 16:00:43-0400 
>  
> OpenFAST input file heading: 
>     Generated with AeroElasticSE FAST driver	 
>  
> Running ElastoDyn. 
> Nodal outputs section of ElastoDyn input file not found or improperly formatted.
> Running BeamDyn.
> Nodal outputs section of BeamDyn input file not found or improperly formatted.
> Running BeamDyn. 
> Nodal outputs section of BeamDyn input file not found or improperly formatted.
> Running BeamDyn. 
> Nodal outputs section of BeamDyn input file not found or improperly formatted.
> Running AeroDyn.
> AD15 Nodal Outputs: Nodal output section of AeroDyn input file not found or improperly formatted. 
> Skipping nodal outputs. 
>    WARNING: WakeMod=11 is a temporary hack. Using new projection method with WakeMod=1. 
> >>> ReadBladeInputs: Computing cant angle (BlCrvAng), AeroProjMod=2 
> >>> ReadBladeInputs: Computing cant angle (BlCrvAng), AeroProjMod=2 
> >>> ReadBladeInputs: Computing cant angle (BlCrvAng), AeroProjMod=2
> Running InflowWind. 
>  
>    Reading a 31x31 grid (315 m wide, 2.5 m to 327.5 m above ground) with a characteristic wind 
>    speed of 6 m/s. This full-field file was generated by TurbSim (v1.50, 25-Sep-2009) on 
>    27-Jun-2024 at 15:57:46.
>  
>    Processed 14250 time steps of 20-Hz grid-field data (712.45 seconds). 
> Running ServoDyn. 
> Running ServoDyn Interface for Bladed Controllers (using Intel Visual Fortran for Windows).
> Using legacy Bladed DLL interface.
>  
> FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
> order of magnitude. BeamDyn may not converge! 
> FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
> order of magnitude. BeamDyn may not converge! 
> FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
> order of magnitude. BeamDyn may not converge! 
>  
>  Time: 0 of 660 seconds.
>                                                                                
> ------------------------------------------------------------------------------
> Running ROSCO-v2.9.0
> A wind turbine controller framework for public use in the scientific field    
> Developed in collaboration: National Renewable Energy Laboratory              
>                             Delft University of Technology, The Netherlands   
> ------------------------------------------------------------------------------ 
> Generator speed:    3.7 RPM, Pitch angle:  -0.3 deg, Power:     0.0 kW, Est. wind Speed:   5.8 m/s 
> 
>  
> FAST_Solution0:CalcOutputs_And_SolveForInputs:SolveOption2:AD_CalcOutput:RotCalcOutput:BEMT_CalcOu 
> tput(node 3, blade 1):UA_CalcOutput:UA_BlendSteady:Temporarily turning off UA due to high angle 
> of attack or low relative velocity. This warning will not be repeated though the condition may 
> persist. 
> 
>  
> FAST_Solution:FAST_AdvanceStates:SrvD_UpdateStates:DLL_controller_call:BladedInterface option was 
> designed for an explicit-loose coupling scheme. Using last calculated values from DLL on all 
> subsequent calls until time is advanced. Warning will not be displayed again. 
> 
>  
> FAST_Solution:FAST_AdvanceStates:AD_UpdateStates:BEMT_UpdateStates:UpdatePhi(node 42, blade 
> 3):BEMT_UnCoupledSolve:There is no valid value of phi for these operating conditions: Vx = 
> 3.1099, Vy = 39.108, rlocal = 101.29, theta = -5.81619E-02, geometric phi = 7.87513E-02. This 
> warning will not be repeated though the condition may persist. (See GeomPhi output channel.) 
> 
> Generator speed:    3.6 RPM, Pitch angle:  -0.4 deg, Power:  3785.7 kW, Est. wind Speed:   6.2 m/s 
>                                                                                                   
>  Time: 10 of 660 seconds.  Estimated final completion at 02:43:27.
> Generator speed:    3.7 RPM, Pitch angle:  -0.3 deg, Power:  3632.1 kW, Est. wind Speed:   6.2 m/s 
>                                                                                                   
>  Time: 20 of 660 seconds.  Estimated final completion at 02:39:35.
> Generator speed:    3.9 RPM, Pitch angle:  -0.4 deg, Power:  4091.4 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 30 of 660 seconds.  Estimated final completion at 14:40:15.
> Generator speed:    4.0 RPM, Pitch angle:  -0.4 deg, Power:  4518.1 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 40 of 660 seconds.  Estimated final completion at 17:00:41.
> Generator speed:    4.0 RPM, Pitch angle:  -0.5 deg, Power:  4641.8 kW, Est. wind Speed:   6.4 m/s 
>                                                                                                   
>  Time: 50 of 660 seconds.  Estimated final completion at 16:22:18.
> Generator speed:    4.0 RPM, Pitch angle:  -0.5 deg, Power:  4652.3 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 60 of 660 seconds.  Estimated final completion at 09:47:34.
> Generator speed:    3.9 RPM, Pitch angle:  -0.4 deg, Power:  4424.3 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 70 of 660 seconds.  Estimated final completion at 03:37:55.
> Generator speed:    3.8 RPM, Pitch angle:  -0.4 deg, Power:  4126.7 kW, Est. wind Speed:   6.2 m/s 
>                                                                                                   
>  Time: 80 of 660 seconds.  Estimated final completion at 03:35:53.
> Generator speed:    3.7 RPM, Pitch angle:  -0.4 deg, Power:  3797.6 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 90 of 660 seconds.  Estimated final completion at 03:31:13.
> Generator speed:    3.4 RPM, Pitch angle:  -0.2 deg, Power:  3136.8 kW, Est. wind Speed:   5.4 m/s 
>                                                                                                   
>  Time: 100 of 660 seconds.  Estimated final completion at 09:24:36.
> Generator speed:    3.3 RPM, Pitch angle:  -0.1 deg, Power:  2822.0 kW, Est. wind Speed:   5.4 m/s 
>                                                                                                   
>  Time: 110 of 660 seconds.  Estimated final completion at 04:04:16.
> Generator speed:    3.3 RPM, Pitch angle:  -0.1 deg, Power:  2688.9 kW, Est. wind Speed:   5.6 m/s 
>                                                                                                   
>  Time: 120 of 660 seconds.  Estimated final completion at 06:26:19.
> Generator speed:    3.5 RPM, Pitch angle:  -0.2 deg, Power:  2917.7 kW, Est. wind Speed:   5.7 m/s 
>                                                                                                   
>  Time: 130 of 660 seconds.  Estimated final completion at 06:10:30.
> Generator speed:    3.6 RPM, Pitch angle:  -0.3 deg, Power:  3216.0 kW, Est. wind Speed:   5.7 m/s 
>                                                                                                   
>  Time: 140 of 660 seconds.  Estimated final completion at 06:36:07.
> Generator speed:    3.6 RPM, Pitch angle:  -0.3 deg, Power:  3472.7 kW, Est. wind Speed:   5.9 m/s 
>                                                                                                   
>  Time: 150 of 660 seconds.  Estimated final completion at 06:04:14.
> Generator speed:    3.7 RPM, Pitch angle:  -0.3 deg, Power:  3610.1 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 160 of 660 seconds.  Estimated final completion at 05:59:04.
> Generator speed:    3.7 RPM, Pitch angle:  -0.4 deg, Power:  3736.9 kW, Est. wind Speed:   6.1 m/s 
>                                                                                                   
>  Time: 170 of 660 seconds.  Estimated final completion at 06:17:24.
> Generator speed:    3.8 RPM, Pitch angle:  -0.4 deg, Power:  4067.0 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 180 of 660 seconds.  Estimated final completion at 05:59:15.
> Generator speed:    4.1 RPM, Pitch angle:  -0.5 deg, Power:  4615.0 kW, Est. wind Speed:   6.7 m/s 
>                                                                                                   
>  Time: 190 of 660 seconds.  Estimated final completion at 05:12:34.
> Generator speed:    4.1 RPM, Pitch angle:  -0.5 deg, Power:  4943.8 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 200 of 660 seconds.  Estimated final completion at 04:30:34.
> Generator speed:    4.0 RPM, Pitch angle:  -0.5 deg, Power:  4792.3 kW, Est. wind Speed:   6.4 m/s 
>                                                                                                   
>  Time: 210 of 660 seconds.  Estimated final completion at 04:16:07.
> Generator speed:    3.9 RPM, Pitch angle:  -0.5 deg, Power:  4581.2 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 220 of 660 seconds.  Estimated final completion at 04:17:08.
> Generator speed:    3.9 RPM, Pitch angle:  -0.5 deg, Power:  4477.8 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 230 of 660 seconds.  Estimated final completion at 04:26:02.
> Generator speed:    3.9 RPM, Pitch angle:  -0.4 deg, Power:  4338.9 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 240 of 660 seconds.  Estimated final completion at 04:24:59.
> Generator speed:    3.7 RPM, Pitch angle:  -0.4 deg, Power:  3949.6 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 250 of 660 seconds.  Estimated final completion at 04:24:03.
> Generator speed:    3.4 RPM, Pitch angle:  -0.2 deg, Power:  3185.9 kW, Est. wind Speed:   5.3 m/s 
>                                                                                                   
>  Time: 260 of 660 seconds.  Estimated final completion at 04:26:54.
> Generator speed:    3.0 RPM, Pitch angle:  -0.0 deg, Power:  2527.2 kW, Est. wind Speed:   5.0 m/s 
>                                                                                                   
>  Time: 270 of 660 seconds.  Estimated final completion at 04:22:47.
> Generator speed:    3.0 RPM, Pitch angle:   0.0 deg, Power:  2108.8 kW, Est. wind Speed:   5.0 m/s 
>                                                                                                   
>  Time: 280 of 660 seconds.  Estimated final completion at 04:22:52.
> Generator speed:    3.1 RPM, Pitch angle:   0.0 deg, Power:  2101.4 kW, Est. wind Speed:   5.1 m/s 
>                                                                                                   
>  Time: 290 of 660 seconds.  Estimated final completion at 04:17:34.
> Generator speed:    3.0 RPM, Pitch angle:   0.1 deg, Power:  2025.1 kW, Est. wind Speed:   4.8 m/s 
>                                                                                                   
>  Time: 300 of 660 seconds.  Estimated final completion at 04:22:10.
> Generator speed:    2.9 RPM, Pitch angle:   0.1 deg, Power:  1915.8 kW, Est. wind Speed:   4.6 m/s 
>                                                                                                   
>  Time: 310 of 660 seconds.  Estimated final completion at 04:16:27.
> Generator speed:    2.7 RPM, Pitch angle:   0.2 deg, Power:  1666.1 kW, Est. wind Speed:   4.5 m/s 
>                                                                                                   
>  Time: 320 of 660 seconds.  Estimated final completion at 04:15:55.
> Generator speed:    2.7 RPM, Pitch angle:   0.2 deg, Power:  1508.4 kW, Est. wind Speed:   4.5 m/s 
>                                                                                                   
>  Time: 330 of 660 seconds.  Estimated final completion at 04:09:55.
> Generator speed:    2.8 RPM, Pitch angle:   0.2 deg, Power:  1546.2 kW, Est. wind Speed:   4.5 m/s 
>                                                                                                   
>  Time: 340 of 660 seconds.  Estimated final completion at 04:21:03.
> Generator speed:    3.0 RPM, Pitch angle:   0.2 deg, Power:  1872.9 kW, Est. wind Speed:   5.1 m/s 
>                                                                                                   
>  Time: 350 of 660 seconds.  Estimated final completion at 04:13:42.
> Generator speed:    3.4 RPM, Pitch angle:  -0.1 deg, Power:  2407.1 kW, Est. wind Speed:   5.6 m/s 
>                                                                                                   
>  Time: 360 of 660 seconds.  Estimated final completion at 04:07:07.
> Generator speed:    3.6 RPM, Pitch angle:  -0.3 deg, Power:  3017.7 kW, Est. wind Speed:   5.8 m/s 
>                                                                                                   
>  Time: 370 of 660 seconds.  Estimated final completion at 04:13:07.
> Generator speed:    3.7 RPM, Pitch angle:  -0.3 deg, Power:  3627.8 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 380 of 660 seconds.  Estimated final completion at 04:23:33.
> Generator speed:    3.9 RPM, Pitch angle:  -0.3 deg, Power:  4285.8 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 390 of 660 seconds.  Estimated final completion at 04:14:20.
> Generator speed:    4.2 RPM, Pitch angle:  -0.4 deg, Power:  5052.9 kW, Est. wind Speed:   6.9 m/s 
>                                                                                                   
>  Time: 400 of 660 seconds.  Estimated final completion at 04:28:28.
> Generator speed:    4.4 RPM, Pitch angle:  -0.6 deg, Power:  5786.7 kW, Est. wind Speed:   7.0 m/s 
>                                                                                                   
>  Time: 410 of 660 seconds.  Estimated final completion at 04:15:18.
> Generator speed:    4.3 RPM, Pitch angle:  -0.6 deg, Power:  5811.4 kW, Est. wind Speed:   6.8 m/s 
>                                                                                                   
>  Time: 420 of 660 seconds.  Estimated final completion at 04:21:42.
> Generator speed:    4.1 RPM, Pitch angle:  -0.5 deg, Power:  5362.1 kW, Est. wind Speed:   6.6 m/s 
>                                                                                                   
>  Time: 430 of 660 seconds.  Estimated final completion at 04:14:15.
> Generator speed:    3.9 RPM, Pitch angle:  -0.5 deg, Power:  4614.6 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 440 of 660 seconds.  Estimated final completion at 04:12:30.
> Generator speed:    3.6 RPM, Pitch angle:  -0.4 deg, Power:  3957.4 kW, Est. wind Speed:   5.9 m/s 
>                                                                                                   
>  Time: 450 of 660 seconds.  Estimated final completion at 04:12:00.
> Generator speed:    3.8 RPM, Pitch angle:  -0.3 deg, Power:  3991.9 kW, Est. wind Speed:   6.4 m/s 
>                                                                                                   
>  Time: 460 of 660 seconds.  Estimated final completion at 04:12:22.
> Generator speed:    3.9 RPM, Pitch angle:  -0.5 deg, Power:  4224.2 kW, Est. wind Speed:   6.4 m/s 
>                                                                                                   
>  Time: 470 of 660 seconds.  Estimated final completion at 04:11:49.
> Generator speed:    4.0 RPM, Pitch angle:  -0.5 deg, Power:  4439.6 kW, Est. wind Speed:   6.3 m/s 
>                                                                                                   
>  Time: 480 of 660 seconds.  Estimated final completion at 04:11:29.
> Generator speed:    3.7 RPM, Pitch angle:  -0.4 deg, Power:  4127.0 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 490 of 660 seconds.  Estimated final completion at 04:11:25.
> Generator speed:    3.6 RPM, Pitch angle:  -0.3 deg, Power:  3651.9 kW, Est. wind Speed:   5.8 m/s 
>                                                                                                   
>  Time: 500 of 660 seconds.  Estimated final completion at 04:12:17.
> Generator speed:    3.5 RPM, Pitch angle:  -0.3 deg, Power:  3378.9 kW, Est. wind Speed:   5.8 m/s 
>                                                                                                   
>  Time: 510 of 660 seconds.  Estimated final completion at 04:10:46.
> Generator speed:    3.5 RPM, Pitch angle:  -0.2 deg, Power:  3110.2 kW, Est. wind Speed:   5.6 m/s 
>                                                                                                   
>  Time: 520 of 660 seconds.  Estimated final completion at 04:11:58.
> Generator speed:    3.5 RPM, Pitch angle:  -0.2 deg, Power:  3104.8 kW, Est. wind Speed:   5.7 m/s 
>                                                                                                   
>  Time: 530 of 660 seconds.  Estimated final completion at 04:12:15.
> Generator speed:    3.6 RPM, Pitch angle:  -0.3 deg, Power:  3220.4 kW, Est. wind Speed:   5.9 m/s 
>                                                                                                   
>  Time: 540 of 660 seconds.  Estimated final completion at 04:10:58.
> Generator speed:    3.7 RPM, Pitch angle:  -0.3 deg, Power:  3521.1 kW, Est. wind Speed:   6.0 m/s 
>                                                                                                   
>  Time: 550 of 660 seconds.  Estimated final completion at 04:11:34.
> Generator speed:    3.8 RPM, Pitch angle:  -0.3 deg, Power:  3825.1 kW, Est. wind Speed:   6.1 m/s 
>                                                                                                   
>  Time: 560 of 660 seconds.  Estimated final completion at 04:10:46.
> Generator speed:    3.8 RPM, Pitch angle:  -0.4 deg, Power:  4026.6 kW, Est. wind Speed:   6.2 m/s 
>                                                                                                   
>  Time: 570 of 660 seconds.  Estimated final completion at 04:11:23.
> Generator speed:    3.9 RPM, Pitch angle:  -0.4 deg, Power:  4423.1 kW, Est. wind Speed:   6.5 m/s 
>                                                                                                   
>  Time: 580 of 660 seconds.  Estimated final completion at 04:11:50.
> Generator speed:    4.3 RPM, Pitch angle:  -0.5 deg, Power:  5250.1 kW, Est. wind Speed:   7.1 m/s 
>                                                                                                   
>  Time: 590 of 660 seconds.  Estimated final completion at 04:11:18.
> Generator speed:    4.5 RPM, Pitch angle:  -0.7 deg, Power:  6193.7 kW, Est. wind Speed:   7.3 m/s 
>                                                                                                   
>  Time: 600 of 660 seconds.  Estimated final completion at 04:12:07.
> Generator speed:    4.6 RPM, Pitch angle:  -0.7 deg, Power:  6809.3 kW, Est. wind Speed:   7.4 m/s 
>                                                                                                   
>  Time: 610 of 660 seconds.  Estimated final completion at 04:12:20.
> Generator speed:    4.5 RPM, Pitch angle:  -0.7 deg, Power:  6678.1 kW, Est. wind Speed:   7.1 m/s 
>                                                                                                   
>  Time: 620 of 660 seconds.  Estimated final completion at 04:11:14.
> Generator speed:    4.2 RPM, Pitch angle:  -0.6 deg, Power:  5863.2 kW, Est. wind Speed:   6.8 m/s 
>                                                                                                   
>  Time: 630 of 660 seconds.  Estimated final completion at 04:10:53.
> Generator speed:    4.1 RPM, Pitch angle:  -0.6 deg, Power:  5362.3 kW, Est. wind Speed:   6.7 m/s 
>                                                                                                   
>  Time: 640 of 660 seconds.  Estimated final completion at 04:10:59.
> Generator speed:    4.2 RPM, Pitch angle:  -0.6 deg, Power:  5331.4 kW, Est. wind Speed:   6.8 m/s 
>                                                                                                   
>  Time: 650 of 660 seconds.  Estimated final completion at 04:10:59.
> Generator speed:    4.3 RPM, Pitch angle:  -0.6 deg, Power:  5582.0 kW, Est. wind Speed:   7.0 m/s 
>                                                                                                   
>  Time: 660 of 660 seconds.  Estimated final completion at 04:10:55.
>                                                                                                    
>  
>  Total Real Time:       12.172 hours 
>  Total CPU Time:        9.1152 hours 
>  Simulation CPU Time:   9.115 hours 
>  Simulated Time:        0.18333 hours 
>  Time Ratio (Sim/CPU):  2.01134E-02 
>  
>  OpenFAST terminated normally.

Is there any bug, change or update regarding the outputs of this new model? If not, could you help me output edgewise/flapwise deflections and root bending moments of blades, please?

Thank you!

Best regards.

**Comment by ptrbortolotti** [comment]
The same question was posted and addressed here https://forums.nrel.gov/t/iea-22-280-rwt-first-set-of-simulations/7178/7
