### ISSUE TITLE
BeamDyn may not converge WARNING

### ISSUE THREAD

**Issue by FannyICY** [IEAWindTask37/IEA-22-280-RWT#92]
Hello, everyone. 

I'm running simulations of the new IEA 22MW WT using OpenFAST and the following message pops up at the beginning of each of my simulations. 

FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 
FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 
FAST_InitializeAll:BD_Init:BD_ValidateInputData:Damping values in blade file are not of similar 
order of magnitude. BeamDyn may not converge! 

I didn't change anything in BeamDyn, i.e. I'm using the reference BeamDyn input files from the repository. 

Could you help me understand and solve this issue, please? 

Thank you!

Best.

**Comment by ptrbortolotti** [comment]
The same question was posted and addressed here https://forums.nrel.gov/t/iea-22-280-rwt-first-set-of-simulations/7178/7
