### ISSUE TITLE
Understanding Load Components [Tower Design]

### ISSUE THREAD

**Issue by Joao97ribeiro** [IEAWindTask37/IEA-22-280-RWT#94]
In the design, the applied loads were 5.4 MN, 0.09 MN, and −8.9 MN in the x, y, and z directions, respectively. The moments were −1.6 MN m, −13.3 MN m, and 10.8 MN m in the x, y, and z directions, respectively.

- The z-load component includes the mass of the RNA and aerodynamic effects, right?
- However, the RNA mass is 1,218,685 kg, which corresponds to approximately 11.96 MN. The aerodynamic impact in the z direction is close to 3 MN (11.96 - 8.9 MN). This value is significant and nearly half of the x direction load (5.4 MN), which was not what I was expecting. Am I missing something?

Thank you in advance

**Comment by ptrbortolotti** [comment]
hello, I spent some time looking into this, and I'm also a little puzzled. the numbers you list here are the ones in the technical report and match what I see in WISDEM. however in WISDEM I don't see much aero loading on z, and so I'm afraid there might be an issue somewhere inside DrivetrainSE where we go from aero hub loads to tower top total loads. I haven't found where yet though. I am on vacation next week and unfortunately it might take a little to get to the bottom of this... I hope this is not super urgent

**Comment by Joao97ribeiro** [comment]
It does seem like there might be an issue with the transition from aero hub loads to tower top total loads in DrivetrainSE. Please take your time; I'll use the values from the technical report for my study.  When you find something, please let me know. 
Thank you for the quick response, and have a great vacation!
