### ISSUE TITLE
Clarification: 3D correction in OpenFAST polars

### ISSUE THREAD

**Issue by jbdv-no** [IEAWindTask37/IEA-22-280-RWT#95]
In section _2.2.4 Airfoil Data_ of the documentation for the reference turbine, it is stated that:

> Finally, note that the airfoil data in WindIO and in this report do not include application of an 
> engineering 3D flow correction model. A 3D correction based on the Snel model is activated by default 
> in HAWC2 [17]. The airfoil input files to OpenFAST include a 3D correction based on the Du-Selig model [27].

Where reference [27] is "Z. Du and M. Selig, A 3-D stall-delay model for horizontal axis wind turbine 
performance prediction".

Is it possible to clarify how the method described in this paper is actually applied when generating
polars for OpenFAST? 

Consider for example the `FFA-W3-360` airfoil with a relative thickness `tc=0.36`, located at `r/R=0.197`
along the blade. Plotting the following airfoil polars from several sources in this repository, give 
the image below:

- `AeroDyn` - `.\OpenFAST\IEA-22-280-RWT\Airfoils\IEA-22-280-RWT_AeroDyn15_Polar_11.dat`
- `HAWC2` - `.\HAWC2\IEA-22-280-RWT-Monopile\data\IEA-22MW_pc.dat` (polar coefficient set 6)
- `QBlade` - `.\QBlade\IEA-22-280-RWT-Monopile\Aero\Polars\FFA-W3-360_FFA-W3-330blend_blend_t35.8_FFA-W3-360_FFA-W3-330blend_blend_t35.8_Polar_RE1.33E+07.plr`
- `WindIO` - `.\windIO\IEA-22-280-RWT.yaml` (`['airfoils'][5]['polars'][0]`)

![polars](https://github.com/user-attachments/assets/b339d0c8-afb8-4f3e-aa50-506f37a7bb12)

Here it is seen that the uncorrected 2D polars from `WindIO` are reproduced by `HAWC2` (corrected internally) and `QBlade`, and that the `AeroDyn` polar includes a 3D correction as stated.

Now, using e.g. the `correction3D` method from the `Polar` class in the `airofoils` module of the `openfast_toolbox`, where the Du-Selig method is implemented, with default options, the 3D corrected results is the same as the 2D result (dashed black line, labelled `Du&Selig c/R=0.052`). Only by increasing `c/R` to `0.23`, am I able to reproduce something that resembles the OpenFAST polar
(dash dotted black line, labelled `Du&Selig c/R=0.23`).

Based on reference 27, equation 12a, and its implementation in `openfast_toolbox`, it makes sense that at a the actual `c/R` ratio, there is no 3D correction, since it is expected only to contribute for `c/R > 0.08` (larger than any `c/R` ratio for this blade). Is the large increase required in `c/R` related to the use of flatback airfoils, that would otherwise have had a much larger chord for their given thickness?

Any clarification, if possible, as to the actual procedures/tools/settings used to define OpenFAST airfoil polars will be much appreciated. (The remainder of the parameters in the OpenFAST polars seem to agree very closely with those generated by the `unsteadyparam` method of the `Polar` class - when using the larger `c/R` value).

**Comment by fzahle** [comment]
Checking the docstring of the correction3D method c/R refers to local chord over local radial location:

https://github.com/OpenFAST/openfast_toolbox/blob/cfb3f1db9c6911bdf9b6fdc0d1bfc6f3973316ac/openfast_toolbox/airfoils/Polar.py#L314

**Comment by jbdv-no** [comment]
Indeed, apologies if I was not clear. I believe I am using the values as described in the docstring.

```python
r_R = 0.197
c_R = 7.206 / 137.8  # = 0.0523
tsr = 9.153 # insensitive not exact value
foil2D.correction3D(r_over_R=r_R, chord_over_r=c_R, tsr=tsr,
                               lift_method="DuSelig", drag_method="None", blending_method="linear_25_45", max_cl_corr=0.25,
                               alpha_max_corr=None, alpha_linear_min=None, alpha_linear_max=None)
```
where `foil2D` is a `Polar` class object created from e.g. WindIO or HAWC2 coefficients

**Comment by jbdv-no** [comment]
🤦‍♂️ Thanks for your patience and apologies for not taking in what I was reading (twice!), everything of course makes perfect sense when using the correct values:

```python
R = 137.8           # blade length
rHub = 7.94 / 2     # hub radius
r_R = 0.197
c = 7.206           # chord @ r/R=0.197
c_rlocal = c / (r_R * R + rHub)  # =  0.232
tsr = 9.153 
foil2D.correction3D(r_over_R=r_R, chord_over_r=c_rlocal, tsr=tsr,
                               lift_method="DuSelig", drag_method="None", blending_method="linear_25_45", max_cl_corr=0.25,
                               alpha_max_corr=None, alpha_linear_min=None, alpha_linear_max=None)
```

![polars_fix](https://github.com/user-attachments/assets/0300a960-1c22-444f-b16d-d9d4e5939196)
